### ISSUE TITLE
Keep upstream pyright main branch in this repository

### ISSUE THREAD

**Issue by jlisee** [sourcegraph/scip-python#44]
It would be awesome if you could keep the `main` branch that `scip-python` is based off in repository for easy comparison.  I am very curious to know how you are diverging from Pyright.  As of this comment I think it's fd98a8a2b964056f7afc616896735689c7cba421 so this link provides the divergence: https://github.com/sourcegraph/scip-python/compare/fd98a8a2b964056f7afc616896735689c7cba421...scip and shows only very minor changes to:

- [packages/pyright-internal/src/analyzer/program.ts](https://github.com/sourcegraph/scip-python/compare/fd98a8a2b964056f7afc616896735689c7cba421...scip#diff-4b21fe9f3dc6101605cdb4bf60cca6bb430e8a8803e067c043cb9862807b812d)
- [packages/pyright-internal/src/analyzer/sourceFile.ts](https://github.com/sourcegraph/scip-python/compare/fd98a8a2b964056f7afc616896735689c7cba421...scip#diff-32dc01623d13bd967864d6e0b14c73f5e490534e7bb337a1d182169b8c670a79)

My main use case is to use this as a project health/bug check tool.  For example if `scip-python` is confused about something it could be:
 - an upstream issue with `Pyright`
 - a fix not yet merged into `scip-python`
 - a bug introduced in the `scip-python` fork

This branch pointer makes that clear.

**Comment by tjdevries** [comment]
The new branch name for the upstream of pyright is `pyright-mirror` that we have in this repo now (so you can see the state of whatever Pyright would be). Additionally, you can look at a diff (via [sourcegraph](https://sourcegraph.com/github.com/sourcegraph/scip-python/-/compare/pyright-mirror...scip) if you'd like) or create a PR (but just don't submit haha) with `pyright-mirror` as the base, and then `scip` as the new repo. That should show all the changes we have.

In general, I'm trying quite hard not to change anything in the pyright libraries themselves (except occasionally making some private method public if I need it, but mostly I've found ways to avoid doing that as well), so the bug is probably with `scip-python` :laughing: . I talk a little bit more about it here: https://github.com/sourcegraph/scip-python#to-compare-upstream-from-pyright

Does that answer everything you were hoping for in this repo? I just did another pull of `pyright` today, since I'm hoping to bump the version quite soon and do a new release (with a lot of fixes and improvements)

**Comment by tjdevries** [comment]
Oh, also I added a file, [pyright-last-sync](https://github.com/sourcegraph/scip-python/blob/scip/pyright-last-sync) just as another marker to make it more obvious in case you wanted to compare to pyright upstream between two different commits.

**Comment by jlisee** [comment]
Awesome thank you!
